### ISSUE TITLE
Suggestions / Questions

### ISSUE THREAD

**Issue by nicolas-chaulet** [Kludex/basesqlmodel#2]
Hey @Kludex !
I played around with this and I have a couple of questions

- using AsyncSession is quite tricky when you have object with relationship and you need to load those upfront (no lazy loading). I was wondering if that would make sense to pass a dictionary of properties and loading methods to the `get` so that we know which relationships to load?
- I struggle to have type hints working on vscode, is this normal?
![image](https://user-images.githubusercontent.com/3178237/149150105-5d8f6b80-c229-4ad3-b5ac-0ca32b8951ce.png)

Thanks!

**Comment by nicolas-chaulet** [comment]
Scrap that, it was a mistake of my own, first question still stands!
>     * I struggle to have type hints working on vscode, is this normal?
>       ![image](https://user-images.githubusercontent.com/3178237/149150105-5d8f6b80-c229-4ad3-b5ac-0ca32b8951ce.png)

**Comment by Kludex** [comment]
Hmm... The way I think about the class I've defined in this package (`Base`) is not to be used in all possible cases. I believe it contains the most used operations. For complex cases, I usually make the query directly.

I guess your suggestion / question also implies changing other methods? If so, how can we change the implementation in a way that it maintains its simplicity? 🤔

**Comment by nicolas-chaulet** [comment]
Yes, I see what you mean, let me push a PR and you tell me what you think. I have had this use case in multiple instances where I want to load relationship data and you're write you can write the whole query but I felt like having that as an option in the get would make some of those situations a little cleaner
